/*
 * This file is generated by jOOQ.
 */
package de.prog3.projektarbeit.jooq;


import de.prog3.projektarbeit.jooq.tables.Player;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;
}
