name: Release
on:
  push:
    branches:
      - "**"

permissions:
  contents: write # for checkout

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          maven-version: 'latest'
      - name: Build with Maven
        run: mvn clean install
      - name: Run Tests
        run: mvn test